Branch1
MishaPnt/Nominal-Money pull request #2
Opened 2021-03-09 15:42 UTC by MishaPnt

2021-03-09 16:05 UTC, DenisAntosh commented on номінали/Program.cs
> +            Console.WriteLine(sumOfMoney1.sumOfCoins);
Please delete comments from this file. Your code shoud be clean

2021-03-09 16:05 UTC, DenisAntosh commented on номінали/Coins.cs
> +
Please delete this new lines in the end of functions

2021-03-09 16:05 UTC, DenisAntosh commented on номінали/Money.cs
> +
The same here, it should be without new lines in the end of the function

2021-03-09 16:05 UTC, DenisAntosh commented on номінали/Nominal.cs
> +
Remove new lines

2021-03-09 16:05 UTC, DenisAntosh commented on номінали/Nominal.cs
> +            sumOfMoney.sumOfCoins = obj1.sumOfMoney.sumOfCoins + obj2.sumOfMoney.sumOfCoins;
you should add a check in case is sumOfCoints is bigger than 100. In this case you should increase grn

2021-03-09 16:05 UTC, DenisAntosh commented on номінали/Nominal.cs
> +            sumOfMoney.sumOfCoins = obj1.sumOfMoney.sumOfCoins - obj2.sumOfMoney.sumOfCoins;
you should add a check in case is sumOfCoints of first object is less than sumOfCoins of the second object. If you have this case in the new object you will have negative value. It is not ok. If in first object coints are less that in second object you should get 100 coins from grv, add to sum of coints and calculate new value

2021-03-09 16:05 UTC, DenisAntosh commented on номінали/Nominal.cs
> +            sumOfMoney.sumOfCoins = obj1.sumOfMoney.sumOfCoins / obj2.sumOfMoney.sumOfCoins;
1. It shoudn't return a SumOfMoney object. It should be double. You should transform all data in coins and devide them. You will have a double number, not a SumOfMoney object
2. Don't forget to check if you devide to 0, it shoudn't be possible

2021-03-09 16:05 UTC, DenisAntosh commented on номінали/Nominal.cs
> +            sumOfMoney.sumOfCoins = obj1.sumOfMoney.sumOfCoins / obj2.sumOfMoney.sumOfCoins;
Also you should call this in the Main. It is not used not, but should be

2021-03-09 16:05 UTC, DenisAntosh commented on номінали/Nominal.cs
> +            sumOfMoney.sumOfCoins = obj1.sumOfMoney.sumOfCoins - obj2.sumOfMoney.sumOfCoins;
Also you should call this in the Main. It is not used not, but should be

2021-03-09 16:05 UTC, DenisAntosh commented on номінали/Nominal.cs
> +            sumOfMoney.sumOfCoins = obj1.sumOfMoney.sumOfCoins + obj2.sumOfMoney.sumOfCoins;
Also you should call this in the Main. It is not used not, but should be

2021-03-09 16:05 UTC, DenisAntosh commented on номінали/Program.cs
> +            номінали.Coins coins = new номінали.Coins(oneCent, twoCent, fiveCent, tenCent, twentyFiveCent, fiftyCent);
please delete "номінали" and add one more using in the top of the file

2021-03-09 16:05 UTC, DenisAntosh commented on номінали/Nominal.cs
> +        {
you should call this in the Main. It is not used not, but should be

2021-03-09 16:05 UTC, DenisAntosh commented on номінали/Nominal.cs
> +        {
you should call this in the Main. It is not used not, but should be

2021-03-09 16:05 UTC, DenisAntosh commented on номінали/Nominal.cs
> +        {
Please change this operator so that it will be multiplied a Nominal object and a number
Also please call it in the main

2021-03-10 08:55 UTC, DenisAntosh commented on номінали/Nominal.cs
> +            sumOfMoney.sumOfCoins = obj1.sumOfMoney.sumOfCoins / obj2.sumOfMoney.sumOfCoins;
I saw your new code, it is not ok
You should transform all data from obj1 and obj2 to coins, then to check of coins from second object is not 0, then to devide coins of first object to coins of second object
![image](https://user-images.githubusercontent.com/41024314/110602736-f45ce580-818e-11eb-926b-eb457b38c66e.png)

2021-03-15 20:51 UTC, DenisAntosh requested changes

2021-03-15 20:51 UTC, DenisAntosh commented on номінали/Nominal.cs
> +
Delete empty line

2021-03-15 20:51 UTC, DenisAntosh commented on номінали/Nominal.cs
> +                double caseForCoins = -100;
its not ok
It should be value - 100
In this case you will have somOfCoins = -100

2021-03-15 20:51 UTC, DenisAntosh commented on номінали/Nominal.cs
> +                sumOfMoney.grn = v;
somOfMoney.grv will be -1
You should have (value - 1)

2021-03-15 20:51 UTC, DenisAntosh commented on номінали/Nominal.cs
> +                sumOfMoney.sumOfCoins = v1;
The same here
somOfMoney.sumOfCoins will be 100
You should have (value + 100)

2021-03-16 08:15 UTC, MishaPnt commented on номінали/Nominal.cs
> +        {
Оperator has been changed
![2021-03-16 (2)](https://user-images.githubusercontent.com/80318045/111276946-9291f500-8640-11eb-8bad-bc0459c07f40.png)

2021-03-16 08:31 UTC, DenisAntosh commented on номінали/Nominal.cs
> +        {
It is not like in the comment that I described below
Now you multiply Nomianl and Nominal
You should multiply Nominal and number
In the end you should return Nominal

2021-03-16 12:37 UTC, DenisAntosh requested changes

2021-03-16 12:37 UTC, DenisAntosh commented on номінали/Nominal.cs
> +                double v1 =  sumOfMoney.grn+100;
A typo here
Should be sumOfMoney.somOfCoins

2021-03-16 12:37 UTC, DenisAntosh commented on номінали/Nominal.cs
> +        {
You should multiply Nominal and number
In the end you should return Nominal

2021-03-16 19:17 UTC, merged